# Translations template for keystone.
# Copyright (C) 2015 OpenStack Foundation
# This file is distributed under the same license as the keystone project.
#
# Translators:
msgid ""
msgstr ""
"Project-Id-Version: Keystone\n"
"Report-Msgid-Bugs-To: https://bugs.launchpad.net/keystone\n"
"POT-Creation-Date: 2015-02-03 06:04+0000\n"
"PO-Revision-Date: 2015-01-05 20:11+0000\n"
"Last-Translator: openstackjenkins <jenkins@openstack.org>\n"
"Language-Team: Chinese (Taiwan) (http://www.transifex.com/projects/p/"
"keystone/language/zh_TW/)\n"
"Language: zh_TW\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: keystone/notifications.py:204
msgid "Failed to construct notifier"
msgstr ""

#: keystone/notifications.py:248
#, python-format
msgid "Failed to send %(res_id)s %(event_type)s notification"
msgstr ""

#: keystone/notifications.py:437
#, python-format
msgid "Failed to send %(action)s %(event_type)s notification"
msgstr ""

#: keystone/catalog/core.py:62
#, python-format
msgid "Malformed endpoint - %(url)r is not a string"
msgstr ""

#: keystone/catalog/core.py:66
#, python-format
msgid "Malformed endpoint %(url)s - unknown key %(keyerror)s"
msgstr "端點 %(url)s 的格式不正確 - 不明的索引鍵 %(keyerror)s"

#: keystone/catalog/core.py:71
#, python-format
msgid ""
"Malformed endpoint '%(url)s'. The following type error occurred during "
"string substitution: %(typeerror)s"
msgstr ""

#: keystone/catalog/core.py:77
#, python-format
msgid ""
"Malformed endpoint %s - incomplete format (are you missing a type notifier ?)"
msgstr ""

#: keystone/common/openssl.py:92
#, python-format
msgid "Command %(to_exec)s exited with %(retcode)s- %(output)s"
msgstr ""

#: keystone/common/openssl.py:120
#, python-format
msgid "Failed to remove file %(file_path)r: %(error)s"
msgstr ""

#: keystone/common/utils.py:239
msgid ""
"Error setting up the debug environment. Verify that the option --debug-url "
"has the format <host>:<port> and that a debugger processes is listening on "
"that port."
msgstr ""

#: keystone/common/cache/core.py:100
#, python-format
msgid ""
"Unable to build cache config-key. Expected format \"<argname>:<value>\". "
"Skipping unknown format: %s"
msgstr ""

#: keystone/common/environment/eventlet_server.py:98
#, python-format
msgid "Could not bind to %(host)s:%(port)s"
msgstr ""

#: keystone/common/environment/eventlet_server.py:184
msgid "Server error"
msgstr "伺服器錯誤"

#: keystone/contrib/endpoint_policy/core.py:129
#: keystone/contrib/endpoint_policy/core.py:228
#, python-format
msgid ""
"Circular reference or a repeated entry found in region tree - %(region_id)s."
msgstr ""

#: keystone/contrib/federation/idp.py:410
#, python-format
msgid "Error when signing assertion, reason: %(reason)s"
msgstr ""

#: keystone/openstack/common/loopingcall.py:95
msgid "in fixed duration looping call"
msgstr "在固定持續時間的迴圈呼叫中"

#: keystone/openstack/common/loopingcall.py:138
msgid "in dynamic looping call"
msgstr "在動態迴圈呼叫中"

#: keystone/openstack/common/policy.py:563
#: keystone/openstack/common/policy.py:843
#, python-format
msgid "Failed to understand rule %s"
msgstr "理解規則 %s 時失敗"

#: keystone/openstack/common/policy.py:573
#, python-format
msgid "No handler for matches of kind %s"
msgstr "類型為 %s 的相符項沒有處理程式"

#: keystone/openstack/common/service.py:269
msgid "Unhandled exception"
msgstr "無法處理的異常狀況"

#: keystone/resource/core.py:393
#, python-format
msgid ""
"Circular reference or a repeated entry found projects hierarchy - "
"%(project_id)s."
msgstr ""

#: keystone/resource/backends/sql.py:101 keystone/resource/backends/sql.py:120
#, python-format
msgid ""
"Circular reference or a repeated entry found in projects hierarchy - "
"%(project_id)s."
msgstr ""

#: keystone/token/provider.py:350
#, python-format
msgid "Unexpected error or malformed token determining token expiry: %s"
msgstr ""

#: keystone/token/persistence/backends/kvs.py:226
#, python-format
msgid ""
"Reinitializing revocation list due to error in loading revocation list from "
"backend.  Expected `list` type got `%(type)s`. Old revocation list data: "
"%(list)r"
msgstr ""

#: keystone/token/providers/common.py:586
msgid "Failed to validate token"
msgstr ""

#: keystone/token/providers/pki.py:47
msgid "Unable to sign token"
msgstr ""
